<?php
/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 * @var \Magedia\Demo\ViewModel\GetResetTimeout $viewModel
 */
    $viewModel = $block->getViewModel();
    $timerSettings = $viewModel->getTimerSettings();
?>
<div class="reset-warning-block">
    <div class="info">
        <imp class="logo" src="#"></imp>
        <a class="back-to-store" href="#">&#8592; Back to Magedia store</a>
    </div>
    <div class="warning-items">
        <p>1. For spam reasons you cannot send emails and import/export data from this demo environment.</p>
        <p>2. This store gets restored from sample data every <span id="reset_timeout"></span> minutes. Next restore
            <span id="reset_timer"></span>.</p>
    </div>
    <div class="more-block">
        <a href="#" class="action-primary more-demos">More demos</a>
    </div>
</div>
<script type="text/x-magento-init">
	{
		"*":{
			"Magedia_Demo/js/reset_timer": {
			    "timerSettings": <?= $timerSettings ?>
			}
		}
	}
</script>
