<?php
/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 * @var \Magento\Framework\Escaper $escaper
 */
$magediaSiteUrl = 'https://magedia.com/';
$marketplaceUrl = 'https://marketplace.magento.com/magedia-m2-pdf-invoice.html';
?>
<div class="reset-warning-block">
    <div class="info">
        <a href="<?= $escaper->escapeUrl($magediaSiteUrl); ?>">
            <img class="logo" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magedia_Demo::images/logo_text.png'));?>">
        </a>
        <a class="back-to-store-block" href="<?= $escaper->escapeUrl($marketplaceUrl); ?>">
            <p class="arrow"> &#8592;</p>
            <p class="back-to-store">Back to Magedia store </p>
        </a>
    </div>
    <div class="warning-icon">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magedia_Demo::images/icon.svg'));?>">
    </div>
    <div class="warning-items">
        <p>1. For spam reasons you cannot send emails and import/export data from this demo environment.</p>
        <p>2. This store gets restored from sample data every <span id="reset_timeout_text"></span>. Next restore
            <span id="reset_timer"></span>.</p>
    </div>
    <div class="more-block" style="display: none!important">
        <a href="#" class="action-primary more-demos">More demos</a>
    </div>
</div>
<script type="text/x-magento-init">
	{
		"*":{
			"Magedia_Demo/js/reset_timer": {}
		}
	}
</script>
